ТЗ11 - 1 итерация
alexexus/java-filmorate pull request #7
Opened 2023-03-16 17:17 UTC by alexexus

2023-03-17 07:09 UTC, kalitva requested changes

2023-03-17 07:09 UTC, kalitva commented on db/filmorate.trace.db
> +2023-03-13 15:14:38 jdbc[3]: exception
Вот эти файлы БД не должны храниться в репе. Добавь в гитигноре `db/`, затем удали папку db и сделай коммит

2023-03-17 07:09 UTC, kalitva commented on pom.xml
> +            <version>1.4.200</version>
Версию не надо указывать

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private final GenreDbStorage genreDbStorage;
Классы дао никак нельзя вайрить друг в друга

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public boolean filmNotExists(long id) {
Инвертированные условие не очень удобно читать, лучше назови `filmExists` и оберни обратно - 
`return result == 1`

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        } else {
Поставь `return` после 109 линия, затем убери else

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            for (Genre genre : genres) {
Используй `JdbcTemplate#batchUpdate` для обновления списка объектов

https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#jdbc-advanced-jdbc

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Film getFilmById(long id) {
Как будет вести себя метод, если объект не найден? Нам нужно чтобы либо вернулся null, либо выбросилось наше `NotFounException`

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +}
Проверь остальные dao на все эти же замечания

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Max(7)
Нет, не надо здесь эти ограничения

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        return genreDbStorage.getAllGenre();
Множественное число `getAllGenres`

2023-03-17 07:09 UTC, kalitva commented on src/main/resources/data.sql
> +INSERT INTO GENRE (GENRE_NAME) VALUES ('Боевик');
После того как удалишь валидации айдишников из моделей, здесь можешь использовать merge вместо insert

2023-03-17 07:09 UTC, kalitva commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS rating_MPA (
`rating_MPA --> raiting_mpa`

2023-03-17 07:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
Перенеси интерфейсы в пакет `dao`. Вообще можешь переименовать суффиксы storage в dao. Не знаю почему у нас на курсе используется storage, правильнее было бы dao

2023-03-17 20:32 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Film getFilmById(long id) {
![image](https://user-images.githubusercontent.com/93264672/226033660-20214dde-2e67-4ea5-a35a-02e5034f907b.png)
Ну так мы в FilmService это проверяем

2023-03-18 15:09 UTC, kalitva requested changes

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +@Component
Эта аннотация не нужна, `@Repository` уже регистрирует класс как спринговый бин

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        addGenre(film.getId(), film.getGenres());
А разве на данный момент в фильме есть айдишник? Его же база генерит...

Как получить сгенерированный айдишник:
https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return getFilmById(film.getId());
Не надо лишних запросов

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                "LEFT JOIN LIKES L on F.FILM_ID = L.FILM_ID GROUP BY F.FILM_ID ORDER BY COUNT(L.FILM_ID) DESC LIMIT ?";
Не очень удобно читать, лучше разбей строку по логическим частям

```
SELECT * FROM FILMS F LEFT 
JOIN RATING_MPA RM ON F.RATING_MPA_ID = RM.RATING_MPA_ID
LEFT JOIN LIKES L on F.FILM_ID = L.FILM_ID 
GROUP BY F.FILM_ID ORDER BY COUNT(L.FILM_ID) DESC LIMIT ?;
```

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private void addGenre(long filmId, List<Genre> genres) {
`addGenre --> addGenres`

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +    public boolean genreNotExists(long id) {
То же самое - переименуй `genreExists`, инвертируй условие. Проверь в остальных dao классах

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +@Component
Лишняя аннотация

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +                "JOIN USERS ON USERS.USER_ID = t1.FRIEND_ID";
Алиасы `t1`, `t2` не годятся, обычно используют первые буквы названия таблицы, например:

```
SELECT * FROM user u
JOIN user_permissions up ON u.id == up.user_id
WHERE u.id = ?
```

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("filmDaoImpl") FilmDao filmDao, @Qualifier("userDaoImpl") UserDao userDao) {
Нам сейчас нужны аннотации `@Qualifier`?

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final GenreDaoImpl genreDaoImpl;
Ну уж создай для новых dao интерфейсы тоже) Это хорошая практика

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public GenreService(@Qualifier("genreDaoImpl") GenreDaoImpl genreDaoImpl) {
Ну здесь то зачем `@Qualifier`?

2023-03-18 15:09 UTC, kalitva commented on src/main/resources/schema.sql
> +ALTER TABLE films ADD FOREIGN KEY (rating_mpa_id) REFERENCES rating_MPA (rating_mpa_id);
`rating_MPA` такой таблицы уже нет, разве не падает с ошибкой? Должно падать

2023-03-18 15:09 UTC, kalitva commented on src/main/resources/data.sql
> +INSERT INTO GENRE (GENRE_NAME) VALUES ('Боевик');
1. Вставляй айдишники явно 
2. Используй `merge` вместо `insert`
 
`MERGE INTO rating_mpa (rating_mpa_id, rating_name) VALUES (1, 'G');`

Иначе при каждом запуске будут одни и те же значения добавляться без надобности

2023-03-18 15:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return getFilmById(film.getId());
`return film`

2023-03-19 16:44 UTC, kalitva approved these changes

2023-03-19 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        film.setGenres(getFilmById(film.getId()).getGenres());
В этом действительно есть необходимость? Предполагается, что в параметре фильма уже есть эти жанры, и вообще: с запросами к БД нужно быть очень внимательным, обращения к БД стоят достаточно дорого в плане времени. Удали этот стэйтмент

2023-03-19 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        genreListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
Слушай, а зачем сортировать, это апи тесты требуют?

2023-03-19 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private List<Genre> getFilmGenres(long filmId) {
Лучше - `getGenresByFilmId`

2023-03-19 22:04 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        genreListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
да

2023-03-20 15:09 UTC, merged